# Generated by Django 4.1.4 on 2023-07-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
