# Generated by Django 4.1.4 on 2023-07-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
