# Generated by Django 4.1.4 on 2023-07-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0008_rename_unique_identifier_post_postid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
