# Generated by Django 4.1.4 on 2023-07-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0010_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.users')),
            ],
        ),
    ]
